[profile.default]
src = "contracts"
out = "out"
libs = ["lib", "node_modules"]
optimizer = true
optimizer_runs = 200
solc = "0.8.20"
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
somnia_testnet = "https://rpc.testnet.somnia.network"
somnia_mainnet = "https://rpc.somnia.network"

[etherscan]
somnia_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://somniascan.xyz/api" }
